Repository kakao-tech-campus-2nd-step3/Team18_FE, pull requests merged in 2024-11, with the labels that each got.

#89 Feat: i18n 번역 데이터 작성, 폴더 및 코드 구조 리팩토링
  src/apis/apiPath.ts
  src/apis/contract/hooks/useGetMyContract.tsx
  src/apis/contract/hooks/usePostContract.tsx
  src/apis/contract/hooks/usePostEmployeeSign.tsx
  src/apis/contract/mock/contract.mock.ts
  src/apis/employee/mock/getMyApplication.mock.ts
  src/apis/postNotice/hooks/usePostNotice.ts
  src/apis/postNotice/mock/postNotice.mock.ts
  src/apis/registerCompany/registerCompany.mock.ts
  src/apis/registerCompany/useRegisterCompany.ts
  src/assets/translator/EmployeeMyPage/ko.ts
  src/assets/translator/EmployeeMyPage/ve.ts
  src/assets/translator/PostNotice/ko.ts
  src/assets/translator/PostNotice/ve.ts
  src/assets/translator/RegisterCompany/ko.ts
  src/assets/translator/RegisterCompany/ve.ts
  src/features/employee/myPage/CardButton.tsx
  src/features/employee/myPage/MyRecruitCard.tsx
  src/features/employee/myPage/MyRecruitList.tsx
  src/mocks/handlers.ts
  src/pages/contract/EmployeeContract/EmployeeContract.tsx
  src/pages/contract/EmployerContract/EmployerContract.tsx
  src/pages/myPage/employee/EmployeeMyPage.stories.tsx
  src/pages/myPage/employee/EmployeeMyPage.tsx
  src/pages/myPage/employee/data/index.mock.ts
  src/pages/postNotice/PostNotice.stories.tsx
  src/pages/postNotice/PostNotice.tsx
  src/pages/registerCompany/RegisterCompany.tsx
  src/routes/path.ts
  src/routes/router.tsx
  src/types/index.d.ts
Labels: feat, refactor

#94 Fix: 잘못된 부분 수정
  package-lock.json
  src/assets/images/profile-image.svg
  src/features/applicants/ApplicantList/ApplicantsTable/index.styles.ts
  src/features/applicants/ApplicantList/ApplicantsTable/index.tsx
  src/features/applicants/ApplicantList/ContractModal/ModalText/index.styles.ts
  src/features/applicants/ApplicantList/ContractModal/ModalText/index.tsx
  src/features/applicants/ApplicantList/ContractModal/index.mock.ts
  src/features/applicants/ApplicantList/ContractModal/index.styles.ts
  src/features/applicants/ApplicantList/ContractModal/index.tsx
  src/features/applicants/ApplicantList/index.tsx
  src/features/companies/CompanyInfo/index.styles.ts
  src/features/companies/CompanyInfo/index.tsx
  src/features/companies/CompanyList/CompaniesTable/index.styles.ts
  src/features/companies/CompanyList/CompaniesTable/index.tsx
  src/features/companies/CompanyList/index.tsx
  src/features/layout/Header/index.stories.tsx
  src/features/layout/index.tsx
  src/features/recruitments/RecruitmentInfo/index.styles.ts
  src/features/recruitments/RecruitmentInfo/index.tsx
  src/features/recruitments/RecruitmentList/RecruitmentsTable/index.styles.ts
  src/features/recruitments/RecruitmentList/RecruitmentsTable/index.tsx
  src/features/recruitments/RecruitmentList/index.tsx
  src/features/registerVisa/VisaRegistrationForm.tsx
  src/features/visaRegistration/index.styles.ts
  src/features/visaRegistration/index.tsx
  src/features/visaRegistration/validateForeignerNumber.ts
  src/pages/applicants/index.mock.ts
  src/pages/applicants/index.stories.tsx
  src/pages/applicants/index.tsx
  src/pages/employee/myPage/EmployeeMyPage.stories.tsx
  src/pages/employee/myPage/EmployeeMyPage.tsx
  src/pages/employee/myPage/data/index.mock.ts
  src/pages/myAccount/employer/index.mock.ts
  src/pages/myAccount/employer/index.styles.ts
  src/pages/myAccount/employer/index.tsx
  src/pages/myCompany/index.mock.ts
  src/pages/myCompany/index.stories.tsx
  src/pages/myCompany/index.styles.ts
  src/pages/myCompany/index.tsx
  src/pages/myPage/employer/EmployerMyPage.stories.tsx
  src/pages/recruit/stories/RecruitCard.stories.tsx
  src/pages/visaRegistration/index.styles.ts
  src/pages/visaRegistration/index.tsx
  src/routes/path.ts
Labels: fix

#100 Feat/#90 이력서 열람 페이지 구현
  README.md
  package-lock.json
  src/apis/apiPath.ts
  src/apis/applicants/hooks/useGetProfileInfo.tsx
  src/apis/applicants/mocks/getApplicantProfile.ts
  src/mocks/handlers.ts
  src/pages/applicantsPage/ApplicantList/ApplicantProfile.tsx
  src/pages/applicantsPage/ApplicantList/ApplicantsTable.tsx
Labels: feat

#103 Feat/#101 i18n 세팅 및 구인글 상세 페이지 적용
  package-lock.json
  package.json
  src/App.tsx
  src/apis/apiPath.ts
  src/apis/recruitmentsDetail/useRecruitmentsDetail.tsx
  src/assets/translator/Languages.ts
  src/assets/translator/Resume/resumeData.ts
  src/assets/translator/i18n.ts
  src/assets/translator/index.ts
  src/features/layout/Header/components/LanguageFilter.tsx
  src/pages/recruit/index.tsx
  src/pages/resume/Resume.tsx
  src/pages/resume/ResumeInput.tsx
  src/routes/path.ts
Labels: feat

#105 Refactor/#102, #106 번역 데이터 수정 및 적용, 회사 등록 버튼 추가
  package-lock.json
  src/assets/translator/Applicants/ContractModal/contractModalData.ts
  src/assets/translator/Applicants/applicantsData.ts
  src/assets/translator/Applicants/ko.ts
  src/assets/translator/Applicants/ve.ts
  src/assets/translator/EmployerMyPage/employerMyPageData.ts
  src/assets/translator/EmployerMyPage/ko.ts
  src/assets/translator/EmployerMyPage/ve.ts
  src/assets/translator/Header/headerData.ts
  src/assets/translator/MyCompany/ko.ts
  src/assets/translator/MyCompany/myCompanyData.ts
  src/assets/translator/MyCompany/ve.ts
  src/assets/translator/RegisterVisa/ko.ts
  src/assets/translator/RegisterVisa/registerVisaData.ts
  src/assets/translator/RegisterVisa/ve.ts
  src/assets/translator/index.ts
  src/features/layout/Header/index.styles.ts
  src/features/layout/Header/index.tsx
  src/features/registerVisa/VisaRegistrationForm.tsx
  src/pages/applicantsPage/ApplicantList/ApplicantsTable.tsx
  src/pages/applicantsPage/ApplicantList/Contract/ModalButtons.tsx
  src/pages/applicantsPage/ApplicantList/Contract/ModalText.tsx
  src/pages/applicantsPage/ApplicantList/index.tsx
  src/pages/myCompanyPage/MyCompany.styles.ts
  src/pages/myCompanyPage/MyCompany.tsx
  src/pages/myCompanyPage/Recruitments/RecruitmentInfo.tsx
  src/pages/myCompanyPage/Recruitments/RecruitmentList.tsx
  src/pages/myCompanyPage/Recruitments/RecruitmentsTable.tsx
  src/pages/myPage/employer/Companies/CompaniesTable.tsx
  src/pages/myPage/employer/Companies/CompanyInfo.styles.ts
  src/pages/myPage/employer/Companies/CompanyList.tsx
  src/pages/myPage/employer/EmPloyerMyPage.tsx
  src/pages/myPage/employer/EmployerMyPage.styles.ts
  src/pages/registerVisa/RegisterVisa.styles.ts
  src/pages/registerVisa/RegisterVisa.tsx
Labels: feat, refactor

#110 Feat/#108 번역데이터 적용 및 Input 컴포넌트 수정
  src/apis/contract/hooks/useGetContractImg.tsx
  src/apis/postNotice/hooks/usePostNotice.ts
  src/apis/registerCompany/hooks/useRegisterCompany.ts
  src/apis/registerCompany/mocks/registerCompany.mock.ts
  src/assets/translator/Contract/contractData.ts
  src/assets/translator/EmployeeMyPage/employeeMyPageData.ts
  src/assets/translator/EmployeeMyPage/ko.ts
  src/assets/translator/EmployeeMyPage/ve.ts
  src/assets/translator/PostNotice/ko.ts
  src/assets/translator/PostNotice/postNoticeData.ts
  src/assets/translator/PostNotice/ve.ts
  src/assets/translator/RegisterCompany/ko.ts
  src/assets/translator/RegisterCompany/registerCompanyData.ts
  src/assets/translator/RegisterCompany/ve.ts
  src/features/employee/myPage/MyRecruitCard.tsx
  src/mocks/handlers.ts
  src/pages/postNotice/PostNotice.tsx
  src/pages/registerCompany/RegisterCompany.tsx
  src/types/index.d.ts
Labels: feat, design, fix

#111 Feat/#108 번역데이터 적용
  src/apis/postNotice/hooks/usePostNotice.ts
  src/assets/translator/EmployeeMyPage/employeeMyPageData.ts
  src/assets/translator/PostNotice/postNoticeData.ts
  src/assets/translator/index.ts
  src/components/common/Input/index.tsx
  src/features/employee/myPage/EmployeeProfile.tsx
  src/pages/contract/EmployeeContract/EmployeeContract.tsx
  src/pages/contract/EmployerContract/EmployerContract.tsx
  src/pages/myPage/employee/EmployeeMyPage.tsx
  src/pages/postNotice/PostNotice.tsx
  src/pages/registerCompany/RegisterCompany.tsx
  src/types/index.d.ts
Labels: fix

#112 style: 근로계약서 서명버튼 스타일 변경
  src/assets/translator/Contract/contractData.ts
  src/components/common/Button/index.tsx
  src/pages/contract/EmployeeContract/EmployeeContract.tsx
  src/pages/contract/EmployerContract/EmployerContract.tsx
Labels: feat, design

#113 Feat/#109 페이지 연결 및 API 연동
  src/apis/apiPath.ts
  src/apis/apply/postApply.mock.ts
  src/apis/apply/useApplyHook.tsx
  src/apis/recruitmentsDetail/mock/cat.jpg
  src/apis/recruitmentsDetail/mock/recruitmentsDetailList.ts
  src/apis/recruitmentsDetail/mock/recruitmentsDetailMockHandler.ts
  src/apis/recruitmentsDetail/mock/requiredFieldCheckData.ts
  src/apis/recruitmentsDetail/mock/requiredFieldCheckHandler.ts
  src/apis/recruitmentsDetail/useRequiredFieldCheck.ts
  src/apis/registerSign/useRegisterSign.ts
  src/apis/resume/postResume.mock.ts
  src/apis/resume/useResumeHook.tsx
  src/assets/translator/Recruit/recruitData.ts
  src/assets/translator/Resume/resumeData.ts
  src/mocks/handlers.ts
  src/pages/apply/applyguide/ApplyGuide.tsx
  src/pages/apply/applypage/ApplyInput.tsx
  src/pages/apply/applypage/ApplyPage.tsx
  src/pages/apply/applypage/useApplyHook.tsx
  src/pages/recruit/RecruitCard.tsx
  src/pages/recruit/RecruitType.ts
  src/pages/recruit/index.tsx
  src/pages/registerSign/RegisterSign.tsx
  src/pages/resume/Resume.tsx
  src/routes/path.ts
Labels: feat

#114 Feat: 근로자 마이페이지 인삿말 설정 및 오류 수정
  src/assets/translator/EmployeeMyPage/employeeMyPageData.ts
  src/features/employee/myPage/EmployeeProfile.tsx
  src/pages/contract/EmployerContract/EmployerContract.tsx
  src/pages/myPage/employee/EmployeeMyPage.tsx
  src/pages/registerCompany/RegisterCompany.tsx
Labels: feat, fix

#116 Fix: handlers.ts import 오류 수정
  src/mocks/handlers.ts
Labels: fix

#118 Feat/#86 메인페이지 필터 API 구현, Pagination 컴포넌트 추가 및 GoogleOAuth API 연동 작업
  src/apis/apiPath.ts
  src/apis/auth/hooks/mutations/useGoogleOAuthMutation.tsx
  src/apis/auth/hooks/mutations/useRegisterMutation.tsx
  src/apis/auth/mutations/useGoogleOAuth.tsx
  src/apis/auth/path.ts
  src/apis/auth/types/request.ts
  src/apis/auth/types/response.ts
  src/apis/home/hooks/queries/queryKeys.ts
  src/apis/home/hooks/queries/useFetchRecruitments.tsx
  src/apis/home/hooks/queries/useFetchSlides.tsx
  src/apis/home/mocks/recruitmentsMockHandler.ts
  src/apis/home/mocks/slidesMockHandler.ts
  src/apis/home/path.ts
  src/apis/home/queries/useFetchRecruitments.tsx
  src/assets/translator/Auth/signInData.ts
  src/assets/translator/Auth/signUpData.ts
  src/assets/translator/Auth/signUpModalData.ts
  src/assets/translator/Home/homeData.ts
  src/assets/translator/i18n.ts
  src/assets/translator/index.ts
  src/components/common/Pagination/index.stories.tsx
  src/components/common/Pagination/index.tsx
  src/components/common/Select/hooks/useGlobalSelect.ts
  src/components/common/Select/hooks/useSelect.ts
  src/components/common/index.ts
  src/features/auth/SignIn/components/SignInButton.tsx
  src/features/auth/SignIn/components/SignInText.tsx
  src/features/auth/SignIn/hooks/useGoogleOAuth.ts
  src/features/auth/SignUp/components/SignUpText.tsx
  src/features/auth/SignUp/components/common/RoleModal.tsx
  src/features/auth/SignUp/components/common/RoleSelector/index.config.tsx
  src/features/auth/SignUp/components/common/RoleSelector/index.tsx
  src/features/home/components/ConditionalRenderer.tsx
  src/features/home/components/Employer.tsx
  src/features/home/components/Worker.tsx
  src/features/home/components/common/RecruitmentFilter.tsx
  src/features/home/components/common/RecruitmentHeader/index.tsx
  src/features/home/components/common/RecruitmentList.tsx
  src/features/home/hooks/useRecruitmentData.ts
  src/features/layout/Header/components/LanguageFilter.tsx
  src/main.tsx
  src/pages/auth/Loading/index.tsx
  src/pages/home/index.tsx
  src/routes/path.ts
  src/types/select.ts
Labels: feat, refactor, fix

#119 Refactor: RecruitDetail storybook 오류 수정
  src/pages/recruit/RecruitDetail.tsx
  src/pages/recruit/stories/RecruitCard.stories.tsx
  src/pages/recruit/stories/index.stories.tsx
Labels: refactor

#126 Feat/#123 마이페이지 접근 제한, 외국인 번호 및 비자 발급 일자 등록 후 페이지 이동 기능 추가
  src/features/registerVisa/VisaRegistrationForm.tsx
  src/routes/guards/RequireAuth.tsx
  src/routes/router.tsx
Labels: feat

#132 Refactor/#130 채용공고 등록 버튼 위치 조정
  src/assets/translator/Applicants/applicantsData.ts
  src/assets/translator/Header/headerData.ts
  src/assets/translator/MyCompany/myCompanyData.ts
  src/features/layout/Header/index.styles.ts
  src/features/layout/Header/index.tsx
  src/pages/myCompanyPage/MyCompany.tsx
  src/pages/myCompanyPage/MyCompanyPage.tsx
  src/pages/myCompanyPage/Recruitments/RecruitmentInfo.tsx
Labels: refactor, design

#133 Refactor/#106 타입 수정 및 사인 등록 페이지 타이틀 추가
  src/assets/translator/registerSign/registerSignData.ts
  src/pages/recruit/RecruitCard.tsx
  src/pages/recruit/RecruitType.ts
  src/pages/recruit/stories/RecruitCard.stories.tsx
  src/pages/registerSign/RegisterSign.tsx
Labels: feat, refactor

#135 Fix: 근로자 마이페이지 버튼 API 연결
  src/apis/employee/mock/myApplicationList.mock.ts
  src/components/common/Button/index.tsx
  src/features/employee/myPage/MyRecruitCard.tsx
  src/types/index.d.ts
Labels: fix

#134 Feat/#127 메인페이지 API 연동
  src/apis/home/hooks/queries/useFetchRecruitments.tsx
  src/apis/home/mocks/recruitmentsMockHandler.ts
  src/apis/home/mocks/slidesMockHandler.ts
  src/apis/home/types/response.ts
  src/components/common/Card/index.tsx
  src/components/common/Image/index.tsx
  src/components/common/Pagination/index.tsx
  src/features/auth/SignIn/hooks/useGoogleOAuth.ts
  src/features/auth/SignUp/components/common/RoleSelector/index.tsx
  src/features/home/components/ConditionalRenderer.tsx
  src/features/home/components/common/RecruitmentCard/index.context.tsx
  src/features/home/components/common/RecruitmentCard/index.tsx
  src/features/home/components/common/RecruitmentCard/sub-components/Detail.tsx
  src/features/home/components/common/RecruitmentCard/sub-components/Salary.tsx
  src/features/home/components/common/RecruitmentCard/sub-components/Title.tsx
  src/features/home/components/common/RecruitmentFilter.tsx
  src/features/home/components/common/RecruitmentList.tsx
  src/features/home/hooks/useRecruitmentData.ts
  src/features/home/types/types.ts
  src/pages/home/index.tsx
Labels: feat, fix

#138 Fix: 회사등록 이미지입력 및 근로자 마이페이지버튼 status 수정
  src/apis/employee/mock/myApplicationList.mock.ts
  src/apis/registerCompany/mocks/registerCompany.mock.ts
  src/features/employee/myPage/MyRecruitCard.tsx
  src/pages/registerCompany/RegisterCompany.tsx
  src/types/index.d.ts
Labels: fix

#139 Fix/#136 마감하기 API 경로 수정 및 고용주 사인 등록 완료 시 버튼 비활성화
  src/apis/apiPath.ts
  src/apis/applicants/mocks/applicants.mock.ts
  src/assets/translator/EmployerMyPage/employerMyPageData.ts
  src/pages/applicantsPage/Applicants.tsx
  src/pages/myCompanyPage/MyCompany.mock.ts
  src/pages/myCompanyPage/MyCompany.styles.ts
  src/pages/myCompanyPage/MyCompany.tsx
  src/pages/myCompanyPage/Recruitments/RecruitmentInfo.styles.ts
  src/pages/myCompanyPage/Recruitments/RecruitmentInfo.tsx
  src/pages/myCompanyPage/Recruitments/RecruitmentsTable.tsx
  src/pages/myPage/employer/Companies/CompaniesTable.styles.ts
  src/pages/myPage/employer/EmPloyerMyPage.tsx
  src/pages/myPage/employer/EmployerMyPage.styles.ts
  src/types/index.d.ts
Labels: refactor, design, fix

#143 Test/#137 메인페이지, 로그인, 회원가입 테스트코드 구현
  package-lock.json
  package.json
  src/__test__/setup.ts
  src/__test__/test-utils.tsx
  src/apis/home/mocks/recruitmentsMockHandler.ts
  src/features/auth/SignIn/components/SignInButton.tsx
  src/features/auth/__test__/SignInButton.test.tsx
  src/features/home/__test__/ConditionRenderer.test.tsx
  src/features/home/__test__/useRecruitmentData.test.tsx
  src/mocks/server.ts
  tsconfig.json
  vite.config.ts
Labels: test

#146 Fix/#144 지원자 목록 페이지 한국어 실력 표시 누락 문제 해결
  src/apis/applicants/mocks/applicants.mock.ts
  src/pages/applicantsPage/ApplicantList/ApplicantsTable.tsx
  src/types/index.d.ts
Labels: fix

#147 Fix/#145 API 명세서에 맞게 변수명 변경
  src/assets/translator/Recruit/recruitData.ts
  src/pages/apply/applypage/ApplyPage.tsx
  src/pages/apply/applypage/useApplyHook.tsx
  src/pages/recruit/RecruitCard.tsx
  src/pages/recruit/RecruitType.ts
  src/pages/recruit/stories/RecruitCard.stories.tsx
Labels: fix

#149 Feat/#142 회사등록 및 근로계약서 API 연결 완료
  src/apis/contract/hooks/usePostEmployeeSign.tsx
  src/pages/contract/EmployeeContract/EmployeeContract.tsx
  src/pages/registerCompany/RegisterCompany.tsx
Labels: feat, fix

#150 Test/#148 외국인 등록 번호 및 비자 발급 일자 등록 폼, Header 테스트 코드 구현
  package-lock.json
  src/assets/translator/RegisterVisa/registerVisaData.ts
  src/features/layout/Header/__test__/Header.test.tsx
  src/features/layout/Header/index.tsx
  src/features/registerVisa/VisaRegistrationForm.tsx
  src/features/registerVisa/__test__/VisaRegistrationForm.test.tsx
Labels: test

#152 Feat/#151 고용주와 근로자 간의 계약 상태에 따라 계약하기 버튼 활성화 제어
  src/apis/applicants/mocks/applicants.mock.ts
  src/assets/translator/Applicants/applicantsData.ts
  src/pages/applicantsPage/ApplicantList/ApplicantsTable.tsx
  src/types/index.d.ts
Labels: feat

#153 Fix: 근로자 마이페이지 버튼 비활성화 및 폴더구조 정리
  src/assets/translator/EmployeeMyPage/employeeMyPageData.ts
  src/features/myPage/employee/components/ButtonGroup.tsx
  src/features/myPage/employee/components/EmployeeProfile.tsx
  src/features/myPage/employee/components/MyRecruitCard.tsx
  src/features/myPage/employee/components/MyRecruitList.tsx
  src/features/myPage/employee/components/ProfileSection.tsx
  src/pages/myPage/employee/EmployeeMyPage.tsx
Labels: fix

#156 Feat: 테스트코드 구현 및 POST 확인 모달창 구현
  src/assets/translator/Contract/contractData.ts
  src/assets/translator/PostNotice/postNoticeData.ts
  src/assets/translator/RegisterCompany/registerCompanyData.ts
  src/features/contract/EmployeeContract/__test__/employeeContract.test.tsx
  src/features/contract/EmployeeContract/components/ContractSection.tsx
  src/features/contract/EmployerContract/__test__/employerContract.test.tsx
  src/features/contract/EmployerContract/components/ContractRegistrationForm.tsx
  src/features/myPage/employee/__test__/MyRecruitList.test.tsx
  src/features/myPage/employee/__test__/ProfileSection.test.tsx
  src/features/postNotice/__test__/PostNoticeForm.test.tsx
  src/features/postNotice/components/PostNoticeForm.tsx
  src/features/registerCompany/__test__/registerCompany.test.tsx
  src/features/registerCompany/components/CompanyRegistrationForm.tsx
  src/pages/contract/EmployeeContract/EmployeeContract.tsx
  src/pages/contract/EmployerContract/EmployerContract.tsx
  src/pages/myPage/employee/EmployeeMyPage.tsx
  src/pages/postNotice/PostNotice.tsx
  src/pages/registerCompany/RegisterCompany.tsx
Labels: feat, test

#157 Test/#154 테스트코드 작성
  src/pages/apply/applypage/__test__/ApplyPage.test.tsx
  src/pages/resume/__test__/Resume.test.tsx
Labels: test
